web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
#    - redis:redis
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: ./wait-for-it.sh postgres:5432 -- /bin/bash /usr/src/app/startup.sh

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /usr/src/app/static
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  build: ./postgres/
#  volumes_from:
#    - data
  ports:
    - "5432:5432"

#redis:
#  restart: always
#  image: redis:latest
#  ports:
#    - "6379:6379"

#data:
#  container_name: database
#  restart: always
#  image: postgres:9.6
#  volumes:
#    - /var/lib/postgresql
#  command: "true"

