# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:44
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        CreateExtension('unaccent'),
    ]
